name: 'Jira Transition Issue'
description: 'Finds the issue key from commit and transitions the issue in Jira'
inputs:
  jira_base_url:
    description: 'Jira base URL'
    required: true
  jira_user_email:
    description: 'Jira user email'
    required: true
  jira_api_token:
    description: 'Jira API token'
    required: true
  issue_transition:
    description: 'Issue transition'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'