name: Jira Test

on:
  push:
    branches:
      - main

jobs:
  jira-test:    # This is the job id, it should not start with a dash.
    runs-on: ubuntu-latest  # Specify the type of machine to run the job on.
    steps:
      - name: Find in Jira ticket
        uses: atlassian/gajira-find-issue-key@master
        id: jira-ticket
        with:
          from: commits

      - name: jira-test
        id: hello
        uses: Hyunju-Sung/actions-jira-process-hj@main
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          issue_transition: 'LIVE QA'
