name: Jira Test

on:
  push:
    branches:
      - main


jobs:
  jira-test:
    runs-on: ubuntu-latest
    name: jira-test
    steps:
      - name: jira-test
        id: hello
        uses: Hyunju-Sung/actions-jira-process-hj@main
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          issue_transition: 'LIVE QA'

